# Generated by Django 2.0.4 on 2018-04-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_profile_is_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='address',
        ),
    ]
