# Generated by Django 2.0.4 on 2018-04-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_auto_20180413_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='screenshot_url',
            new_name='screenshot_uuid',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
