# Generated by Django 2.0.4 on 2018-04-14 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0004_auto_20180414_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dateCreated',
            new_name='created',
        ),
        migrations.AddField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
