# Generated by Django 2.0.4 on 2018-04-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0005_auto_20180414_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('UNPAID', 'unpaid'), ('PAID', 'paid'), ('SHIPPED', 'shipped'), ('DELIVERED', 'delivered')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], max_length=255),
        ),
    ]
