# Generated by Django 2.0.4 on 2018-04-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0008_auto_20180415_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='screenshot_uuid',
            field=models.UUIDField(),
        ),
    ]
