# Generated by Django 2.0.4 on 2018-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0010_auto_20180415_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sendee',
            new_name='order_uuid',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='by_user',
            field=models.BooleanField(default=False),
        ),
    ]
