# Generated by Django 2.0.4 on 2018-04-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0011_auto_20180418_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='by_user',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
